### ISSUE TITLE
DB Table Merge

### ISSUE THREAD

**Issue by delashu** [delashu/COVID_vax_monitoring#4]
Merge the vaccine table with the state demographic table.

**Comment by patrickkwang** [comment]
I'm curious what we're imagining this merged table to look like. Is there just one row for each state? Or will time/date be a factor as well? What are some example columns?

**Comment by delashu** [comment]
Yes, each row will represent one state. 
Some example columns will include state-level demographic data (population, age groupings, sex proportions, race percentages, etc.)
